"""MobKit Python SDK.

Usage::

    from meerkat_mobkit import MobKit, MobKitRuntime, MobKitBuilder
    from meerkat_mobkit import DiscoverySpec, PreSpawnData, SessionQuery
    from meerkat_mobkit import SessionAgentBuilder, SessionBuildOptions
    from meerkat_mobkit.errors import MobKitError, RpcError, NotConnectedError
    from meerkat_mobkit.types import StatusResult, CapabilitiesResult
    from meerkat_mobkit.events import MobEvent, AgentEvent

Module authoring helpers are available via::

    from meerkat_mobkit.helpers import ModuleSpec, define_module, ...
"""
from __future__ import annotations

# Builder + Runtime
from .builder import MobKit, MobKitBuilder
from .runtime import JobsHandle, MobKitRuntime, MonitorsHandle, ToolCaller
from .live import (
    ActiveLiveChannelHandle,
    ActiveLiveChannelConnection,
    ExperimentalLiveChannelStatus,
    ExperimentalLiveExecutionProfileConfig,
    ExperimentalLiveGatewayConfig,
    LIVE_EXECUTION_CLIENT_CONTEXT_V1,
    LIVE_EXECUTION_FUNCTION_BRIDGE_V1,
    LIVE_EXECUTION_IDENTITY_V1,
    LiveAssistantOutputAddress,
    LiveAuthBindingRef,
    LiveChannelCapabilities,
    LiveChannelHandle,
    LiveReplacementRequired,
    LiveContinuityMode,
    LivePlaybackCompleteResult,
    LiveExecutionIdentityV1,
    LiveExecutionMode,
    LivePlaybackOwnerReadiness,
    LivePlaybackOwner,
    PendingLiveChannelHandle,
    LiveTransportBootstrap,
    live_open_execution_identity_params,
    live_execution_mode_capability,
    supports_live_execution_mode,
    supports_live_execution_identity_v1,
)
from .jobs import (
    DetachedJobAuthority,
    DetachedJobContext,
    DetachedJobExecution,
    DetachedJobResult,
)
from .identity_first_models import (
    AgentBuildContext,
    AgentBuildDraft,
    CompletionCursor,
    CompletionProgress,
    ConsoleIdentityRecord,
    DurableAgentSpec,
    ExternalToolDef,
    IdentityBootstrapCounts,
    IdentityBootstrapEntry,
    IdentityBootstrapMode,
    IdentityBootstrapState,
    IdentityBootstrapStatus,
    MAX_IDENTITY_BACKGROUND_WARM_CONCURRENCY,
    RoleMigrationDeclaration,
)

# Identity-first customizer boundary (public contract; the per-identity
# equivalent of SessionAgentBuilder). The submodule paths keep working.
from .identity_first_providers import AgentCustomizerProtocol

# Data models
from .models import DiscoverySpec, PreSpawnData, SessionBuildOptions, SessionCreatedContext, SessionQuery

# Agent builder protocol (public contract — CallbackDispatcher is internal)
from .agent_builder import SessionAgentBuilder

# Errors
from .errors import (
    MOB_EVENTS_STALE_CURSOR_CODE,
    CAPABILITY_UNAVAILABLE_CODE,
    CONSOLE_TIMELINE_REPLAY_UNAVAILABLE_CODE,
    LEASE_LOST_CODE,
    MEMORY_BACKEND_UNAVAILABLE_CODE,
    STORAGE_RESOLUTION_CODE,
    WORKGRAPH_CONFLICT_CODE,
    WORKGRAPH_UNAVAILABLE_CODE,
    CapabilityUnavailableError,
    ConsoleTimelineReplayUnavailableError,
    ContractMismatchError,
    LeaseLostError,
    MemoryBackendUnavailableError,
    MobEventsStaleError,
    MobKitError,
    NotConnectedError,
    RpcError,
    StorageResolutionError,
    TransportError,
    WorkGraphConflictError,
    WorkGraphUnavailableError,
)

# Typed return models
from .types import (
    AgentMemoryForgetResult,
    AgentMemoryManifestResult,
    AgentMemoryRecallResult,
    AgentMemoryRecord,
    AgentMemoryRecordMeta,
    AgentMemoryUpdateResult,
    CallToolResult,
    CapabilitiesResult,
    CatalogEntry,
    CrossMobContactEntry,
    DeliveryHistoryResult,
    DeliveryResult,
    ErrorCategory,
    ErrorEvent,
    RESOLUTION_ERROR_CATEGORIES,
    EventEnvelope,
    EventQuery,
    GatingAuditEntry,
    GatingDecisionResult,
    GatingEvaluateResult,
    GatingPendingEntry,
    HelperResult,
    KeepAliveConfig,
    MEMBER_STATE_ACTIVE,
    MEMBER_STATE_BROKEN,
    MEMBER_STATE_COMPLETED,
    MEMBER_STATE_RETIRING,
    MEMBER_STATE_UNKNOWN,
    FailureRecord,
    FrameRecord,
    LoopIterationRecord,
    LoopRecord,
    MemberHealth,
    MemberReloadResult,
    MemberSnapshot,
    MemoryIndexResult,
    MemoryQueryResult,
    MemoryStoreInfo,
    MobMemberStatus,
    MobpackAgentDefinitionsResult,
    MobpackApplyOperationResult,
    MobpackCatalogsResult,
    MobpackDeployCommandResult,
    MobpackDeployResult,
    MobpackDiagnostic,
    MobpackDisplayRow,
    MobpackDraftDeleteResult,
    MobpackDraftGetResult,
    MobpackDraftHistoryResult,
    MobpackDraftListResult,
    MobpackDraftRow,
    MobpackDraftSaveResult,
    MobpackExportResult,
    MobpackImportResult,
    MobpackSkillsCatalogResult,
    MobpackSourceFile,
    MobpackSourceResult,
    MobpackTemplatesResult,
    MobpackToolsCatalogResult,
    MobpackValidationResult,
    IdentityResolvedToolsResult,
    MobRun,
    MobRunSnapshot,
    MobRunStatus,
    MobStructuralEvent,
    StepRecord,
    MobUnreachablePeer,
    ModelsCatalogResult,
    PeerConnectivitySnapshot,
    PersistedEvent,
    ProfileCapabilities,
    ProviderDefaults,
    ReconcileEdgesReport,
    ReconcileResult,
    RediscoverReport,
    MemberProgressSnapshot,
    RichMemberSnapshot,
    RoutingResolution,
    RuntimeCapabilities,
    RuntimeRouteResult,
    SendMessageResult,
    SpawnMemberResult,
    SpawnResult,
    StatusResult,
    StorageSlotSummary,
    StorageSummary,
    SubscribeResult,
    UnifiedAgentEvent,
    UnifiedModuleEvent,
    WorkGraphAttentionBinding,
    WorkGraphAttentionReassignResult,
    WorkGraphEdge,
    WorkGraphEventEntry,
    WorkGraphGoalResult,
    WorkGraphItem,
    WorkGraphItemsResult,
    WorkGraphSnapshotResult,
)

# Typed events
from .events import (
    AgentEvent,
    Event,
    EventStream,
    MobEvent,
    RunCompleted,
    RunFailed,
    RunStarted,
    TextComplete,
    TextDelta,
    ToolCallRequested,
    ToolExecutionCompleted,
    ToolExecutionStarted,
    ToolResultReceived,
    TurnCompleted,
    TurnStarted,
    UnknownEvent,
)

# Config modules (importable as meerkat_mobkit.auth, etc.)
from .config import auth, event_log, memory, runtime_store, session_store

# Rich tool-result content blocks for callback tool handlers.
from .tool_content import (
    ToolResultContent,
    image_block,
    image_blob_block,
    text_block,
    tool_content,
)

__all__ = [
    # Builder + Runtime
    "MobKit",
    "MobKitBuilder",
    "MobKitRuntime",
    "JobsHandle",
    "MonitorsHandle",
    "DetachedJobAuthority",
    "DetachedJobContext",
    "DetachedJobExecution",
    "DetachedJobResult",
    "IdentityBootstrapMode",
    "RoleMigrationDeclaration",
    "IdentityBootstrapState",
    "IdentityBootstrapCounts",
    "IdentityBootstrapEntry",
    "IdentityBootstrapStatus",
    "ConsoleIdentityRecord",
    "MAX_IDENTITY_BACKGROUND_WARM_CONCURRENCY",
    # Identity-first customizer boundary
    "AgentBuildContext",
    "AgentBuildDraft",
    "AgentCustomizerProtocol",
    "DurableAgentSpec",
    "ExternalToolDef",
    # Turn-completion identity
    "CompletionCursor",
    "CompletionProgress",
    # Tool-result content blocks
    "text_block",
    "image_block",
    "image_blob_block",
    "tool_content",
    "ToolResultContent",
    # Data models
    "DiscoverySpec",
    "PreSpawnData",
    "SessionBuildOptions",
    "SessionCreatedContext",
    "SessionQuery",
    # Agent builder
    "SessionAgentBuilder",
    # Errors
    "MobKitError",
    "TransportError",
    "RpcError",
    "MobEventsStaleError",
    "MOB_EVENTS_STALE_CURSOR_CODE",
    "CAPABILITY_UNAVAILABLE_CODE",
    "CONSOLE_TIMELINE_REPLAY_UNAVAILABLE_CODE",
    "LEASE_LOST_CODE",
    "MEMORY_BACKEND_UNAVAILABLE_CODE",
    "STORAGE_RESOLUTION_CODE",
    "WORKGRAPH_CONFLICT_CODE",
    "WORKGRAPH_UNAVAILABLE_CODE",
    "CapabilityUnavailableError",
    "ConsoleTimelineReplayUnavailableError",
    "LeaseLostError",
    "MemoryBackendUnavailableError",
    "StorageResolutionError",
    "WorkGraphConflictError",
    "WorkGraphUnavailableError",
    "ContractMismatchError",
    "NotConnectedError",
    # Typed return models
    "StatusResult",
    "CapabilitiesResult",
    "LIVE_EXECUTION_IDENTITY_V1",
    "LIVE_EXECUTION_FUNCTION_BRIDGE_V1",
    "LIVE_EXECUTION_CLIENT_CONTEXT_V1",
    "ActiveLiveChannelHandle",
    "ActiveLiveChannelConnection",
    "PendingLiveChannelHandle",
    "ExperimentalLiveChannelStatus",
    "ExperimentalLiveExecutionProfileConfig",
    "LiveAssistantOutputAddress",
    "LiveAuthBindingRef",
    "ExperimentalLiveGatewayConfig",
    "LiveChannelCapabilities",
    "LiveChannelHandle",
    "LiveReplacementRequired",
    "LiveContinuityMode",
    "LivePlaybackCompleteResult",
    "LiveExecutionIdentityV1",
    "LiveExecutionMode",
    "LivePlaybackOwnerReadiness",
    "LivePlaybackOwner",
    "LiveTransportBootstrap",
    "live_open_execution_identity_params",
    "live_execution_mode_capability",
    "supports_live_execution_mode",
    "supports_live_execution_identity_v1",
    "StorageSlotSummary",
    "StorageSummary",
    "ReconcileResult",
    "SpawnResult",
    "SpawnMemberResult",
    "SendMessageResult",
    "SubscribeResult",
    "KeepAliveConfig",
    "EventEnvelope",
    "RoutingResolution",
    "DeliveryResult",
    "DeliveryHistoryResult",
    "AgentMemoryRecord",
    "AgentMemoryRecordMeta",
    "AgentMemoryRecallResult",
    "AgentMemoryManifestResult",
    "AgentMemoryUpdateResult",
    "AgentMemoryForgetResult",
    "MemoryQueryResult",
    "MemoryStoreInfo",
    "MemoryIndexResult",
    "MEMBER_STATE_ACTIVE",
    "MEMBER_STATE_RETIRING",
    "MEMBER_STATE_BROKEN",
    "MEMBER_STATE_COMPLETED",
    "MEMBER_STATE_UNKNOWN",
    "MemberSnapshot",
    "MobRun",
    "MobRunStatus",
    "MobStructuralEvent",
    "StepRecord",
    "FailureRecord",
    "FrameRecord",
    "LoopRecord",
    "LoopIterationRecord",
    "RuntimeRouteResult",
    "GatingEvaluateResult",
    "GatingDecisionResult",
    "GatingAuditEntry",
    "GatingPendingEntry",
    "CallToolResult",
    "CatalogEntry",
    "CrossMobContactEntry",
    "HelperResult",
    "MobMemberStatus",
    "MobRunSnapshot",
    "MobUnreachablePeer",
    "ModelsCatalogResult",
    "MobpackAgentDefinitionsResult",
    "MobpackApplyOperationResult",
    "MobpackCatalogsResult",
    "MobpackDeployCommandResult",
    "MobpackDeployResult",
    "MobpackDiagnostic",
    "MobpackDisplayRow",
    "MobpackDraftDeleteResult",
    "MobpackDraftGetResult",
    "MobpackDraftHistoryResult",
    "MobpackDraftListResult",
    "MobpackDraftRow",
    "MobpackDraftSaveResult",
    "MobpackExportResult",
    "MobpackImportResult",
    "MobpackSkillsCatalogResult",
    "MobpackSourceFile",
    "MobpackSourceResult",
    "MobpackTemplatesResult",
    "MobpackToolsCatalogResult",
    "MobpackValidationResult",
    "IdentityResolvedToolsResult",
    "PeerConnectivitySnapshot",
    "ProviderDefaults",
    "MemberProgressSnapshot",
    "RichMemberSnapshot",
    "RuntimeCapabilities",
    "ProfileCapabilities",
    "ErrorCategory",
    "ErrorEvent",
    "RESOLUTION_ERROR_CATEGORIES",
    "EventQuery",
    "PersistedEvent",
    "UnifiedAgentEvent",
    "UnifiedModuleEvent",
    "ReconcileEdgesReport",
    "RediscoverReport",
    "ToolCaller",
    "WorkGraphItem",
    "WorkGraphEdge",
    "WorkGraphAttentionBinding",
    "WorkGraphSnapshotResult",
    "WorkGraphItemsResult",
    "WorkGraphGoalResult",
    "WorkGraphAttentionReassignResult",
    "WorkGraphEventEntry",
    # Typed events
    "Event",
    "MobEvent",
    "AgentEvent",
    "EventStream",
    "RunStarted",
    "RunCompleted",
    "RunFailed",
    "TurnStarted",
    "TextDelta",
    "TextComplete",
    "ToolCallRequested",
    "ToolResultReceived",
    "TurnCompleted",
    "ToolExecutionStarted",
    "ToolExecutionCompleted",
    "UnknownEvent",
    # Config modules
    "auth",
    "event_log",
    "memory",
    "runtime_store",
    "session_store",
]
