load("@crates//:defs.bzl", "aliases", "all_crate_deps")

load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_proc_macro", "rust_test")



filegroup(

    name = "cargo_manifest",

    srcs = ["Cargo.toml"],

    visibility = ["//visibility:public"],

)



filegroup(

    name = "package_runfiles",

    srcs = glob(["Cargo.toml", "**/*"], exclude = ["BUILD", "BUILD.bazel"], allow_empty = True),

    visibility = ["//visibility:public"],

)



rust_library(
    name = "mobkit_extension_state",
    aliases = aliases(package_name = "crates/mobkit-extension-state"),
    crate_name = "mobkit_extension_state",
    crate_root = "src/lib.rs",
    crate_features = [],
    edition = "2024",
    compile_data = [
        "Cargo.toml",
    ],
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//visibility:public"],
    rustc_env = {
        "CARGO_PKG_VERSION": "0.8.46",
        "CARGO_MANIFEST_DIR": "./crates/mobkit-extension-state",
    },
    proc_macro_deps = all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        proc_macro = True,
    ),
    deps = all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        normal = True,
    ),
)

rust_test(
    name = "mobkit_extension_state_unit_test",
    aliases = aliases(
        package_name = "crates/mobkit-extension-state",
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "mobkit_extension_state",
    crate_root = "src/lib.rs",
    crate_features = [],
    edition = "2024",
    compile_data = [
        "Cargo.toml",
    ],
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//visibility:public"],
    rustc_env = {
        "CARGO_PKG_VERSION": "0.8.46",
        "CARGO_MANIFEST_DIR": "./crates/mobkit-extension-state",
    },
    tags = [
        "fast",
        "unit",
    ],
    size = "small",
    data = [
        ":package_runfiles",
    ],
    env = {
        "RUST_MIN_STACK": "16777216",
    },
    proc_macro_deps = all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        proc_macro = True,
        proc_macro_dev = True,
    ),
    deps = all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "conformance_test",
    aliases = aliases(
        package_name = "crates/mobkit-extension-state",
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_name = "conformance",
    crate_root = "tests/conformance.rs",
    crate_features = [],
    edition = "2024",
    compile_data = [
        "Cargo.toml",
    ],
    srcs = [
        "tests/conformance.rs",
    ],
    visibility = ["//visibility:public"],
    rustc_env = {
        "CARGO_PKG_VERSION": "0.8.46",
        "CARGO_BIN_NAME": "conformance",
        "CARGO_MANIFEST_DIR": "./crates/mobkit-extension-state",
    },
    tags = [
        "fast",
    ],
    size = "small",
    data = [],
    env = {
        "RUST_MIN_STACK": "16777216",
    },
    proc_macro_deps = all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        proc_macro = True,
        proc_macro_dev = True,
    ),
    deps = [
        "//crates/mobkit-extension-state:mobkit_extension_state",
    ] + all_crate_deps(
        package_name = "crates/mobkit-extension-state",
        normal = True,
        normal_dev = True,
    ),
)

test_suite(
    name = "fast_tests",
    tests = [
        ":conformance_test",
        ":mobkit_extension_state_unit_test",
    ],
)
