"""Deprecated — use meerkat_mobkit instead."""
from meerkat_mobkit import (  # noqa: F401
    MobkitAsyncTypedClient,
    MobkitRpcError,
    MobkitTypedClient,
    ModuleDefinition,
    ModuleSpec,
    ModuleTool,
    build_console_experience_route,
    build_console_modules_route,
    build_console_route,
    build_console_routes,
    build_module_spec,
    create_gateway_async_transport,
    create_gateway_sync_transport,
    create_http_transport,
    decorate_module_spec,
    decorate_module_tool,
    define_module,
    define_module_spec,
    define_module_tool,
)
