#!/usr/bin/env bash
# Bump every published/install-facing version to match the Cargo workspace.
# Usage: ./scripts/bump-sdk-versions.sh [VERSION]
# If VERSION is omitted, reads from Cargo.toml workspace.package.version.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ $# -ge 1 ]; then
    VERSION="$1"
else
    VERSION=$(cargo metadata --manifest-path "$ROOT/Cargo.toml" \
        --no-deps --format-version 1 \
        | jq -r '.packages[] | select(.name == "meerkat-mobkit") | .version')
fi

echo "Bumping SDK versions to $VERSION"

# Portable sed -i (macOS vs GNU)
sedi() {
    if sed --version >/dev/null 2>&1; then
        sed -i "$@"
    else
        sed -i '' "$@"
    fi
}

# Python SDK
sedi "s/^version = \".*\"/version = \"$VERSION\"/" "$ROOT/sdk/python/pyproject.toml"
echo "  Python SDK: $VERSION"

# TypeScript SDK (if present)
if [ -f "$ROOT/sdk/typescript/package.json" ]; then
    node -e "
const fs = require('fs');
const p = '$ROOT/sdk/typescript/package.json';
const pkg = JSON.parse(fs.readFileSync(p, 'utf8'));
pkg.version = '$VERSION';
fs.writeFileSync(p, JSON.stringify(pkg, null, 2) + '\n');
"
    echo "  TypeScript SDK: $VERSION"
fi

# TypeScript SDK lockfile — the root package version lives in two places
# (top-level + packages['']). Keep it in lockstep so it can't drift (it was
# stale at 0.7.4 across 0.7.5–0.7.7).
if [ -f "$ROOT/sdk/typescript/package-lock.json" ]; then
    node -e "
const fs = require('fs');
const p = '$ROOT/sdk/typescript/package-lock.json';
const lock = JSON.parse(fs.readFileSync(p, 'utf8'));
lock.version = '$VERSION';
if (lock.packages && lock.packages['']) lock.packages[''].version = '$VERSION';
fs.writeFileSync(p, JSON.stringify(lock, null, 2) + '\n');
"
    echo "  TypeScript SDK lockfile: $VERSION"
fi

# Bazel build rules embed the crate version via rustc_env, which feeds
# env!("CARGO_PKG_VERSION") in the bazel-built RELEASE binaries (e.g. their
# `--version` output). Keep it in lockstep so released gateways don't report a
# stale version (this drifted to 0.7.4 across 0.7.5–0.7.7 before being caught).
#
# This used to sed exactly one file, meerkat-mobkit/BUILD.bazel, which made it a
# hand-maintained enumeration of a generated artifact. It silently missed
# mobkit-store-conformance/BUILD.bazel, so that file drifted one release behind
# from the moment the crate was added: at 0.8.19 it still declared 0.8.18, and
# CI's stale-generated-file check was red on main until it was regenerated by
# hand. Re-derive from cargo metadata instead, which covers every crate in the
# workspace including ones added later.
if [ -f "$ROOT/scripts/generate-bazel-rust-builds.mjs" ] && command -v node >/dev/null 2>&1; then
    # Run FROM $ROOT: the generator resolves the workspace with `git rev-parse`
    # against the caller's cwd, so invoking it by absolute path from elsewhere
    # would target whichever repo the caller happened to be standing in.
    ( cd "$ROOT" && node scripts/generate-bazel-rust-builds.mjs >/dev/null )
    echo "  Bazel BUILD.bazel regenerated for all workspace crates: $VERSION"
else
    # No generator reachable, which is the case for the release-script test
    # fixture. Still bump EVERY BUILD.bazel found rather than one hardcoded
    # path: the whole defect being fixed here is a hand-maintained enumeration
    # of a generated artifact, and a fallback that reintroduces it fixes
    # nothing. Skipping silently would be worse still, since the release would
    # then commit a version its build files disagree with.
    while IFS= read -r build_file; do
        sedi -E "s/\"CARGO_PKG_VERSION\": \"[^\"]*\"/\"CARGO_PKG_VERSION\": \"$VERSION\"/g" "$build_file"
        echo "  Bazel ${build_file#"$ROOT/"} CARGO_PKG_VERSION: $VERSION"
    done < <(find "$ROOT" -name BUILD.bazel -not -path '*/node_modules/*' -not -path '*/target/*' | sort)
fi

# The root Bazel module is published as a first-class package surface and is
# checked by verify-version-parity.sh. Keep its module() version in the same
# canonical bump path as the SDK and rustc_env versions.
if [ -f "$ROOT/MODULE.bazel" ]; then
    sedi -E '/^module\(/,/^\)/ s/(version = ")[^"]*(",)/\1'"$VERSION"'\2/' "$ROOT/MODULE.bazel"
    echo "  Bazel MODULE.bazel version: $VERSION"
fi

# Installation docs are executable release inputs too: a stale 0.x Cargo
# requirement never selects a newer minor line. Keep every canonical Rust
# install snippet on the same version as the package surfaces above.
for DOC in "$ROOT/docs/quickstart.mdx" "$ROOT/docs/sdks/rust.mdx"; do
    if [ -f "$DOC" ]; then
        sedi -E 's/(meerkat-mobkit = ")[^"]*(")/\1'"$VERSION"'\2/g' "$DOC"
        echo "  Rust install docs ($(basename "$DOC")): $VERSION"
    fi
done

echo "Done"
